name: Peter Bednár
favicon: null
layout_spectrum: 0.8852642858400941
typography_spectrum: 0.37051511416211724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1d1d3'
    - '#2e5051'
    - '#0c1514'
    - '#a89f98'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
