name: Peter Bednár
favicon: null
layout_spectrum: 0.8852642858400941
typography_spectrum: 0.37051511416211724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6476173936389387
  lightness: 0.9452520415652543
  saturation: 0.7605808118823916
  rhythmicContrast: 0.2384813386015594
purpose: []
